
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const SORT_ACTION ='SORT_ACTION'


//profile
export const GET_PROFILE = 'GET_PROFILE';
export const GET_CURRENT_PROFILE = 'GET_CURRENT_PROFILE';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';
export const PROFILE_ERROR = 'PROFILE_ERROR';

//feedback
export const GET_FEEDBACK = 'GET_FEEDBACK';
export const GET_FEEDBACK_BY_ID = 'GET_FEEDBACK_BY_ID';
export const DELETE_FEEDBACK='DELETE_FEEDBACK'
export const FEEDBACK_ERROR = 'FEEDBACK_ERROR';

//users
export const GET_USERS = 'GET_USERS';
export const USERS_ERROR='USERS_ERROR'
export const UPDATE_USER_STATUS = 'UPDATE_USER_STATUS';
export const UPDATE_USER = 'UPDATE_USER'
//dashboard
export const DASHBOARD_ERROR="DASHBOARD_ERROR"
export const GET_DASHBOARD_DATA="GET_DASHBOARD_DATA"

//reports
export const GET_REPORTS = 'GET_REPORTS';
export const GET_REPORT = 'GET_REPORT';
export const DELETE_REPORT = 'DELETE_REPORT';
export const REPORT_ERROR = 'REPORT_ERROR';


//forgot password
export const SUCCESS_FORGOTPASSWORD='SUCCESS_FORGOTPASSWORD';
export const SUCCESS_VERIFY_CODE='SUCCESS_VERIFY_CODE';
export const SUCCESS_RESET_PASSWORD = 'SUCCESS_RESET_PASSWORD';
export const UPDATE_CATEGORY ='UPDATE_CATEGORY'


//notifications
export const GET_NOTIFICATIONS = 'GET_NOTIFICATIONS';


//trucks
export const GET_TRUCKS = 'GET_TRUCKS'
export const GET_TRUCKS_DETAIL_BY_ID = 'GET_TRUCKS_DETAIL_BY_ID'
export const TRUCK_ERROR = 'TRUCK_ERROR'




